# Generated by Django 4.1.6 on 2023-05-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_Administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidoP', models.CharField(max_length=200)),
                ('apellidoM', models.CharField(max_length=200)),
                ('edad', models.IntegerField(default=0, max_length=3)),
                ('contrasenia', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado_Tableta',
            fields=[
                ('id_Encargado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidoP', models.CharField(max_length=200)),
                ('apellidoM', models.CharField(max_length=200)),
                ('edad', models.IntegerField(default=0, max_length=3)),
                ('contrasenia', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('id_Adminustrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App50Amigos.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_Mesa', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(choices=[('terraza', 'Terraza'), ('jardin', 'Jardin'), ('comedor', 'Comedor'), ('balcon', 'Balcon')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_Orden', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ordenar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App50Amigos.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id_Platillo', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('entrada', 'Entrada'), ('plato_fuerte', 'Plato Fuerte'), ('postre', 'Postre'), ('helado', 'Helado')], max_length=20)),
                ('costo', models.IntegerField(default=0, max_length=5)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=1000)),
                ('id_Administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App50Amigos.administrador')),
                ('id_Menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App50Amigos.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Tableta',
            fields=[
                ('id_Tableta', models.AutoField(primary_key=True, serialize=False)),
                ('id_Encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App50Amigos.encargado_tableta')),
            ],
        ),
        migrations.CreateModel(
            name='PlatilloEnOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App50Amigos.ordenar')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App50Amigos.platillo')),
            ],
        ),
        migrations.AddField(
            model_name='ordenar',
            name='platillos',
            field=models.ManyToManyField(through='App50Amigos.PlatilloEnOrden', to='App50Amigos.platillo'),
        ),
        migrations.AddField(
            model_name='orden',
            name='id_Tableta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App50Amigos.tableta'),
        ),
        migrations.CreateModel(
            name='Estar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(blank=True, max_length=20)),
                ('id_Mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App50Amigos.mesa')),
                ('id_Tableta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App50Amigos.tableta')),
            ],
        ),
    ]
