# Generated by Django 4.1.6 on 2023-05-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App50Amigos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='id_Adminustrador',
            new_name='id_Admin',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='id_menu',
            new_name='id_Menu',
        ),
        migrations.AlterField(
            model_name='platillo',
            name='categoria',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('plato_fuerte', 'Plato Fuerte'), ('postre', 'Postre'), ('bebida', 'Bebida'), ('helado', 'Helado')], max_length=20),
        ),
    ]
