# Generated by Django 4.1.6 on 2023-05-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App50Amigos', '0003_alter_administrador_id_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id_Administrador',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
        ),
    ]
