# Generated by Django 3.2.12 on 2023-05-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App50Amigos', '0004_alter_administrador_id_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id_Administrador',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
