# Generated by Django 4.1.6 on 2023-05-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App50Amigos', '0005_alter_administrador_id_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='nombre',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
