# Generated by Django 4.1.6 on 2023-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App50Amigos', '0007_alter_tableta_id_tableta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='encargado_tableta',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
