# Generated by Django 4.1.6 on 2023-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App50Amigos', '0008_alter_administrador_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='costo',
            field=models.IntegerField(default=0),
        ),
    ]
