# Generated by Django 4.1.6 on 2023-06-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App50Amigos', '0009_alter_platillo_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='id_Orden',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
